# Generated by Django 4.1.3 on 2022-11-04 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_th', models.CharField(default='', max_length=255)),
                ('title_eng', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='', max_length=50)),
                ('institute', models.CharField(default='', max_length=125)),
                ('major', models.CharField(default='', max_length=50)),
                ('year', models.IntegerField(default=0)),
                ('callnumber', models.CharField(default='', max_length=50)),
                ('pages', models.IntegerField(default=1)),
                ('abstract', models.TextField(default='')),
                ('file', models.FileField(default='', upload_to='static/pdf/')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=35)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('number', models.IntegerField(default=1)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.thesis')),
            ],
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='อาจารย์', max_length=35)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='ที่ปรึกษาหลัก', max_length=35)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesisapp.thesis')),
            ],
        ),
    ]
